# Identifiant unique du nœud (entier &gt;= 0)
node.id=1
# Le rôle : à la fois broker et controller (mode &quot;combined&quot; sur une seule machine)
process.roles=broker,controller
# Quorum des controllers (nous n&#39;en avons qu&#39;un)
controller.quorum.voters=1@localhost:9093
# Adresse d&#39;écoute pour les clients (port 9092) et pour le contrôleur (port 9093)
listeners=PLAINTEXT://:9092,CONTROLLER://:9093
# Adresse annoncée aux clients (utilisée par les producers/consumers pour se reconnecter)
advertised.listeners=PLAINTEXT://localhost:9092
# Nom du listener pour les communications inter-controller
controller.listener.names=CONTROLLER
# Mapping des protocoles
listener.security.protocol.map=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
# Répertoire des logs (TRÈS important : évitez /tmp qui est nettoyé au reboot !)
log.dirs=/home/yesser-belhajali/kafka-data/logs
# Pour un environnement de TP — on autorise la création automatique de topics
auto.create.topics.enable=true
# Tolérance à 1 broker (sinon les topics internes refusent de démarrer)
offsets.topic.replication.factor=1
transaction.state.log.replication.factor=1
transaction.state.log.min.isr=1
log.cleaner.max.compaction.lag.ms=5000
